### ISSUE TITLE
Windows 10 - Authentication error (80090326) ?

### ISSUE THREAD

**Issue by rsyqvthv** [ghDaYuYu/foo_discogs#1]
I was use 2.32 original with a long time out of work, glad to see you are keep up to update, and I saw someone has proofed this mod is working, but my problem is I couldn't get it re-authorized in the config page:

when I click Authorize button in config page, it shows me following error after a long time loading:

```
(FATAL) Error: Network exceptionNetwork authentication error (80090326) 
(url: https://api.discogs.com/oauth/request_token)

[ESCAPE to close]
```

how can I deal with this? thanks.

**Comment by ghDaYuYu** [comment]
This a general diagnostic you may try...
- Firewall is allowing communication
- Computer time and date is correct
- TLS 1.2 is functional on your system

Hope this helps,
Regards

(If you are running Windows 7, update TLS to v1.2.
There are a few guides around, a simple method would be installing
kb3140245 security update + TLS 'easyfix')

**Comment by rsyqvthv** [comment]
Thanks for your reply, as I don't have Firewall to block things and my computer time is auto sync with internet which I don't think that will be my case, 

so for the last point you mentioned: TLS 1.2, Im not quite familiar with, so I tried research and it makes me more confused:

most of the result coming up is regarding the TLS setting on server side, but my issue is on client side, would that be the reason to my problem?

or maybe you would like to give me a clue to determine my TLS settings are correct? 

my system is Window 10 LTSC 2019, which I think it active the TLS 1.2 by default regarding my research.

Thanks again. :)

**Comment by ghDaYuYu** [comment]
Hello again, :)

Yes, TLS 1.2 should be enabled by default...
I can´t think of any clues right now, sorry, just couple commands if you are willing to investigate this a bit further.

I would suggest testing the handshaking from curl and ciphers from PowerShell.
From command line and c:\windows\system32 folder...
`curl -vk --tlsv1.2 --tls-max 1.2 "https://api.discogs.com/database/search?q=queen"`

optionally I would retry including also this option  --ciphers ECDHE-RSA-AES256-GCM-SHA384

There should be a final 401 UNAUTHORIZED, and a  line for 'SSL/TLS handshake complete' at the beginning.

If the handshaking failed I would check the cipher from Windows PowerShell:
`(Get-TlsCipherSuite).Name`

And look for cipher TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

In the case handshaking is ok (without 80090326 error) and the cipher is available
I would consider another set of tests ; )

If you  are willing to investigate in your own, I will be glad to know about your findings.
In any case, there should be a solution to this issue soon at component's forum at hydrogenaud.io.

Regards

**Comment by ghDaYuYu** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue.

Thank you!

**Comment by Melodycloudu** [comment]
While I'm not the original poster, I am seemingly running into the same issue on Windows 10. On Foobar V2.24.1 tried on V25 and no luck as well

**Comment by ghuDaYuYu** [comment]
It might be worth a try visiting the Discogs website, logging in to your user account and revoking the authorization.
Register again the component on Foobar.
Some people reported that disabling the VPN temporarily during this process solved some authorization issues.
