### ISSUE TITLE
FATAL Error - JSON Parser

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#10]
Here's the error and the release:
```
(FATAL) Error: Error loading release 6963878: JSON Parser ExceptionError parsing release credits.

[ESCAPE to close]
```
https://www.discogs.com/The-Cribs-Mens-Needs-Womens-Needs-Whatever/release/6963878

**Comment by ghDaYuYu** [comment]
Comma is missing in A6, B1 ?
Patched from Fatal to Skipped to continue parsing rest of fields.

**Comment by stephen147** [comment]
Thanks for the very quick fix!
