### ISSUE TITLE
Tags are not updated

### ISSUE THREAD

**Issue by mrror** [ghDaYuYu/foo_discogs#101]
If I "create" a release with files from different releases the tags are not updated, even if the preview says so. I've tried with various setting changes but nothing seems to work.

https://github.com/ghDaYuYu/foo_discogs/assets/6650443/cacdfcee-c0d1-4bac-86dc-b8c57733854f

**Comment by ghuDaYuYu** [comment]
The 'Difference view' just shows how Discogs database differs from your local tags. To check the expected outcome, try switching to the 'Results view'.

**Comment by mrror** [comment]
> The 'Difference view' just shows how Discogs database differs from your local tags. To check the expected outcome, try switching to the 'Results view'.

I also do the "Write tags" at the end of the video, the part before is just to show that the component "sees" the wanted changes (but then doesn't apply them)

**Comment by ghuDaYuYu** [comment]
What I mean is that the 'Difference view' part in the video shows the  ~~wanted~~ changes that can _potentially_ be applied. To verify the desired outcome you want to switch to 'Results view'.

**Comment by mrror** [comment]
Right. So, the "Difference view" shows the correct potential new tags, while the "Results view" shows everything as already is

**Comment by ghuDaYuYu** [comment]
Then the tag mapping is defined that way, no update needed.
I guess you just need to spend some more time familiarizing yourself with this software.

**Comment by mrror** [comment]
Tag mapping settings are the default ones, which always worked for original component.

![tagmapping](https://github.com/ghDaYuYu/foo_discogs/assets/6650443/3d414876-1ec2-43da-bebb-683c53b32270)

**Comment by ghuDaYuYu** [comment]
Those default mapping are not very favorable for the current use case, quite handy to avoid unintentionally overwriting local values though. It worked (under some circumstances) in the original component, still wondering if that was a feature or a bug.

I believe this issue can be closed now that the opening issue is solved.

Regards!

**Comment by mrror** [comment]
Just to understand, why would these mappings not overwrite local values? To my understanding, that's what "write" does, and the tags match. Thanks!

**Comment by ghuDaYuYu** [comment]
It is just the current convention (#82).
Of course the terminology might evolve in future updates.
