### ISSUE TITLE
Bonus track is not getting found

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#11]
Here's the release.

https://www.discogs.com/TI-Urban-Legend/release/11321706

![image](https://user-images.githubusercontent.com/14054664/110870128-c3ca9800-82c3-11eb-95b2-5a4e08831ef4.png)

**Comment by ghDaYuYu** [comment]
This result came out here for release 11321706

![ti 11b](https://user-images.githubusercontent.com/62167612/112729251-86a10f80-8f2b-11eb-98f3-185b54a258a0.JPG)

**Comment by stephen147** [comment]
Silly me, I was parsing a different id.

User error on this one ;)
