### ISSUE TITLE
Clicking next - The loading artist releases still continues

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#12]
1. Click next in the find release dialog (assuming the id is populated).
2. The match track dialog appears, but..
2. The loading artist releases dialog still continues.

**Comment by gitgetgot** [comment]
FYIO, you could use [GifCam](https://blog.bahraniapps.com/gifcam/) to show us what you're experiencing.

So you're saying, the the loading of artist never stops? 
It looks "normal" here? Maybe I tried a different artist?

It looks this way here: the artist is only shortly loaded. Or maybe I misread your post?
![3](https://user-images.githubusercontent.com/974980/130361330-6743baa7-9f64-4b66-8527-3ca1abb31ddd.gif)

**Comment by ghuDaYuYu** [comment]
Please, check if this is still happening in the latest release.
I've just run a few test where only artist, release and artwork preview are loaded.
You can also check changing the new auto-load options added recently,
regards

**Comment by stephen147** [comment]
Seems to be all okay, thanks for the fix. :)
