### ISSUE TITLE
Unable to disable writing DISCOGS_RELEASE_ID

### ISSUE THREAD

**Issue by armak** [ghDaYuYu/foo_discogs#120]
The option to disable writing `DISCOGS_RELEASE_ID` is either disabled, or does not work. Normally for some reason clicking on the right where the action column is, these options are disabled for a few of the ID tags. However, they can still be disabled for most of them by clicking on the left side. Even then however, the state doesn't properly disable for `DISCOGS_RELEASE_ID`. I do not want to write any of these ID tags into my files.

![image](https://github.com/user-attachments/assets/b506b808-0619-4074-8b44-89694d75cf74)

Note how the "write" action still remains enabled for the release ID.

**Comment by ghuDaYuYu** [comment]
The user interface is quite consistent... alright not 100% consistent.
Grayed-out items usually mean 'disabled' not 'quirky item'.

The disabled 'Write tags' in the Preview means 'nothing to do'. That state is usually unknown in the previous dialog, so probably not related to your hack.
I see... unless coming back from the preview panel.

About the DISCOGS_RELEASE_ID...
The 'I do not want to write any of these ID tags into my files' is a fair argument, and will be taken into consideration.
This issue will be closed soon. Might move it to the discussion area, as a feature request, idk yet.
Thanks for your feedback.

**Comment by frogworth** [comment]
@armak I think @ghuDaYuYu is working on a different workflow for this, but tags like that which are greyed out can still be changed by holding down shift when you click.

**Comment by ghuDaYuYu** [comment]
Hi [frogworth](https://github.com/frogworth),
You are right again! Let´s move the issue to the discussion...
