### ISSUE TITLE
Crashes when pressing Write tags or Preview tags

### ISSUE THREAD

**Issue by rrroscar** [ghDaYuYu/foo_discogs#17]
in Match Tracks window obvs. Files are flac, they play fine and pass f2k's integrity test.

https://www.discogs.com/release/7957627
https://www.discogs.com/release/6179428

Both uses headers and one of them has a hidden track, but that has worked fine with other releases, so I have no clue as to why, I'm afraid.

**Comment by ghDaYuYu** [comment]
I am clueless also... I arranged 12 flacs for release 7957627 (all tags enabled) updating without issues. 
Would you like to post the crash report files (from fb2k crash reports folder) so I try to debug this further?

**Comment by rrroscar** [comment]
Yups (sorry, I'm late, life...). I made new flacs, still the same. 
[dump.zip](https://github.com/ghDaYuYu/foo_discogs/files/6447183/dump.zip)

**Comment by ghDaYuYu** [comment]
I believe it would be best to first find out if another component is conflicting with foo_discogs. You can try running just foo_discogs under a fresh portable installation (or renaming other component´s folders in your setup).
The .dmp stack trace did not point me to any particular foo_discogs routine, it just shows a crash calling set_string_ function (a member of fb2k api pfc library). Sorry but that's all I can do for now but please report back after your tests and I will be glad to help I can.
Sorry for late response,
cheers

**Comment by ghDaYuYu** [comment]
Closing this issue. No crash reports regarding this issue have been reported since April.
