### ISSUE TITLE
Bug - Featuring artists don't get parsed on first run

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#18]
Using this for TITLE:
```
$trim($pputs(title,$replace(%TRACK_TITLE%, '('Original Mix')',))$if(%DISCOGS_CREDIT_FEATURING%,$pget(title)' feat. '%DISCOGS_CREDIT_FEATURING%,$pget(title))))
```

Running the plugin on the first time doesn't get the featuring artists. Only on the 2nd run it gets them.

Try these settings and the release I'm trying to parse.
**This always crashes on the 2nd run too like the bug I reported [yesterday](https://github.com/ghDaYuYu/foo_discogs/issues/19).**

Release: https://www.discogs.com/Ciara-Goodies/release/4811871
Settings: [test settings.zip](https://github.com/ghDaYuYu/foo_discogs/files/6534548/test.settings.zip)

---

Also, is it possible to do this for TITLE? `Title (feat. Artist 1, Artist 2 & Artist 3)` instead of just the title?

**Comment by stephen147** [comment]
I've fixed it.

Is this a bug with `%DISCOGS_CREDIT_FEATURING%`?

```
$trim($pputs(Vartitle,$replace(%TRACK_TITLE%, '('Original Mix')',)))$trim($pputs(varFeat,$filter($flatten($multi_if($any($multi_strcmp($sextend(%<<TRACK_CREDITS_SHORT_ROLES>>%,%<<RELEASE_CREDITS_SHORT_ROLES>>%),'Featuring')),$multi_if($put(aj,$sextend(%<<TRACK_CREDITS_ARTISTS_JOIN>>%,%<<RELEASE_CREDITS_ARTISTS_JOIN>>%)),$joinnames($put(an,$sextend(%<<TRACK_CREDITS_ARTISTS_NAME>>%,%<<RELEASE_CREDITS_ARTISTS_NAME>>%)),$get(aj)),$get(an)),)),))$if($any($pget(varFeat)),$pget(Vartitle) 'feat. '$join($pget(varFeat)),$pget(Vartitle)))
```

It still crashes on 2nd run as per that other issue. Non-related but I do think that `%DISCOGS_CREDIT_FEATURING%` is a bug?

**Comment by ghDaYuYu** [comment]
Great #18 & #19 bug descriptions, stephen147.
I have run your test cases, there is a bug indeed.
At first glance the bug crashes the component while comparing RELEASE_CREDITS_SHORT_ROLES related tags (featuring, vocals, remixed by) old/new values.
I will try to fix this issue (or at least some test cases) in the next few days.

**Comment by stephen147** [comment]
Thanks for your hard work. If you have a donate link handy I'd be more than happy to contribute for your efforts.

**Comment by ghuDaYuYu** [comment]
Seams to still be working after all this while... 🌊
