### ISSUE TITLE
Crash with DISCOGS_CREDIT_FEATURING

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#19]
Here are the settings that are crashing foobar. 

[crashing settings.zip](https://github.com/ghDaYuYu/foo_discogs/files/6528917/crashing.settings.zip)

And the release I'm trying to get.

https://www.discogs.com/release/2702206

When I remove:
```
$flatten($multi_if($any($multi_strcmp($sextend(%<<TRACK_CREDITS_SHORT_ROLES>>%,%<<RELEASE_CREDITS_SHORT_ROLES>>%),'Featuring')),$multi_if($put(aj,$sextend(%<<TRACK_CREDITS_ARTISTS_JOIN>>%,%<<RELEASE_CREDITS_ARTISTS_JOIN>>%)),$joinnames($put(an,$sextend(%<<TRACK_CREDITS_ARTISTS_NAME>>%,%<<RELEASE_CREDITS_ARTISTS_NAME>>%)),$get(aj)),$get(an)),))
```

It works. 

Strange that this is the default and it doesn't crash when I use the default settings but it does with my attached settings.

The important part of the crash report seems to be:
```
Crash location:
Module: ucrtbase
Offset: 4CE60h
Symbol: "strlen" (+30h)
```

**Comment by stephen147** [comment]
This seems to be fixed with https://www.discogs.com/release/2702206 when I reenable the `DISCOGS_CREDIT_FEATURING` field.

Have you addressed this? If so I suppose you can close this.

**Comment by ghDaYuYu** [comment]
Sorry for late replay, Stephen. I had a look at the issue. It seams that some tags need a tag value to be already available so they get available in a 'second pass' but not totally sure about it...

**Comment by stephen147** [comment]
At least I haven't had a crash. It's strange about the 2nd pass thing.

**Comment by ghDaYuYu** [comment]
Yes, the important bit is if it does not crash any more... I looked at the source in tags.cpp a while ago, vaguely remember that  'featuring', 'vocals' and 'remixed by' needed TRACK_CREDITS_SHORT_ROLES already present. They seam to be quit useful even if a second pass is needed. At though about extending to other roles like Engineered by, etc. not sure if I come back to that soon though.

**Comment by ghDaYuYu** [comment]
Just run a test with your test data, is not crashing
Please reopen the issue if you still experiencing crashes related to this issue.

**Comment by stephen147** [comment]
No, no crashing, even after clearing the cache.
