### ISSUE TITLE
Proposal - Option for track lengths to the left on the right pane in Match Tracks dialog

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#20]
This would leave it easier to check the lengths to have an option in the preferences.

![image](https://user-images.githubusercontent.com/14054664/119678597-8fcd3080-be37-11eb-8d70-620df7540e54.png)

**Comment by ghDaYuYu** [comment]
Proposal accepted 👍 

![snip_left_len](https://user-images.githubusercontent.com/62167612/120520989-bc072500-c3d4-11eb-9f75-c44ca5f6af29.jpg)

**Comment by stephen147** [comment]
Thanks. ;) Will the filenames be centred like that?

**Comment by ghDaYuYu** [comment]
Column headers can be dragged now.
The center alignment is optional (from the context menu).
It´s late addition to v16, will hopefully be evolving in next versions.

**Comment by stephen147** [comment]
Thanks very much. The track lengths opposite was much needed. I will be testing the new release but it works great so far.
