### ISSUE TITLE
SUGGESTION - File type for the settings file

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#21]
I accidentally overwrote a file I shouldn't and thought of this idea.

Not sure if it's easily doable or would break things for other users but I'd like to propose this idea.

![image](https://user-images.githubusercontent.com/14054664/119734388-d429f200-be72-11eb-8824-f187bee39cfa.png)

**Comment by ghDaYuYu** [comment]
New feature available now from v16 ([commit](
https://github.com/ghDaYuYu/foo_discogs/commit/f44c3afbeda3a235ae513850adcb0d103f38543a)).
Feel free to test it!

**Comment by stephen147** [comment]
Thanks, it seems to work great. Thanks for adding.
