### ISSUE TITLE
SUGGESTION - Selection of items in the right match tracks window minics on the left

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#22]
See attached.

![image](https://user-images.githubusercontent.com/14054664/119883770-d00bdc00-bf27-11eb-8dc7-6679a2e52eeb.png)

**Comment by ghDaYuYu** [comment]
Not sure to follow you in this one, sorry... as you mention the up & down buttons, being then able to move both selections simultaneously pressing those buttons?

**Comment by stephen147** [comment]
Just when the right item is selected the left corresponding row is also highlighted. Basically that it follows what's selected on the right.

Obviously, this wouldn't happen when clicking on an item in the left pane as it will be required. But maybe this would be good so that you know when the two same items line up.

Hopefully, you can understand my gibberish. 😎

**Comment by ghDaYuYu** [comment]
That´s what I though at first, as a visual reference 👍 
Not a very nice solution but could be simple to line up single selections by double clicking items on the left 😎
Or may you have already have something figured out

**Comment by stephen147** [comment]
I'm thinking of another program that does this. https://www.filebot.net/ it works quite well.

**Comment by ghDaYuYu** [comment]
... hopefully the new panel with alternate background color will make it easier to match tracks and files. List row with greater heights would be nice also.

**Comment by gitgetgot** [comment]
@stephen147 

> Just when the right item is selected the left corresponding row is also highlighted. Basically that it follows what's selected on the right.

I find this useful too, but what should happen, when you have moved a file in right panel, say, two rows up or down ?
Should the left selected track stay selected? or updated to the new position on the right? or just disapear?

> Obviously, this wouldn't happen when clicking on an item in the left pane as it will be required. But maybe this would be good so that you know when the two same items line up.

If this feature request is for better visual identification of the selected items, 
I think, selecting an item on whatever side should select the item on the counterpart too.

Now, the new alternate background will maybe help some ppl. a little, but we all get older and blinder 8-]
For me, the plain white background was not that irritating as the new alternate colours. Everyones eyes are different...

@ghuDaYuYu 
Did you remove the MOVE UP/MOVE DOWN buttons under the left pane? 
They are sometimes very important where ppl. use keybord(-shortcuts) as a prefered imput device.

Could you bring them back ? (And IF, could you add shortcuts, say MOVE'**U**'P / MOVE D'**O**'WN, so ppl. don't have to TAB their way through the buttons...)

**Comment by ghuDaYuYu** [comment]
Added to the To Do, maybe as an additional column rather than two list side by side...
Maybe one day, not soon though, noted!

**Comment by stephen147** [comment]
Hiya, :)

Would it be possible to open this again?

Here's what I was talking about in mp3tag.

![2023 02 03 (22-06-24)](https://user-images.githubusercontent.com/14054664/216720023-3ec2f434-6628-4aa0-bbb3-db15b8d61615.gif)

**Comment by ghuDaYuYu** [comment]
Hi there! Sure!

**Comment by ghuDaYuYu** [comment]
Bear with me while I try to fix the coffee machine, I am experiencing some brain fog at the moment...

Just as introduction, the Discogs list and the local file list controls are derived from fb2k SDK libPPUI library control classes.
libPPUI will not happily accept modifications leading to rare, non-standard list behaviors. One can expect to be hacking the way trough the standard list control event flow while implemented this sort of features.

Also, I wonder whether implementing this feature would introduce some uncertainty to the UI (context menu actions, drag and drop, key presses,... action will be (intuitively) affected?). 

I just need to convince myself that the mod effort is justified (IMHO only in one, rare case that you did not mention, will come back to his later).

**Comment by ghuDaYuYu** [comment]
My understanding so far is to change the behavior of the lists so that when one right list item is selected, then the item occupying the same position on the left pane gets also selected?

**Comment by ghuDaYuYu** [comment]
In my experience, I just missed this sort of assistance in the 'manage artwork' panel, with releases containing large amount of items, when resizing the dialog to its max size will still leave items above and below the panel boundaries. At the time, a new 'row number' column was added to solve this problem.

I wonder if is that sort of scenario that we are trying to solve here, as in my opinion, the alternative row background colors should suffice to line up items.

**Comment by stephen147** [comment]
Yes clicking a row on the right lane will highlight the same row on the left pane.

But, I was maybe thinking of a comparison column showing the match percentage of the opposing row instead. It would be a handy visual to see how close each track is.

**Comment by ghuDaYuYu** [comment]
Alternative row background colors is not enough? I can understand it better in your latest GIF, where some columns are quite far apart.

**Comment by stephen147** [comment]
The way mp3tag does it is the ideal solution. Row colours would be fine but not as good.

**Comment by ghuDaYuYu** [comment]
I disagree, in fact, I do not like it a all, I find it quite inconsistent. Of course, it possible I change my mind, but this component will most probably never mimic that functionality.
There are too many uncertainties (you did not answer some questions in my latest posts), and I can sense lots of additional patches required to integrate the change and maintain the UI cohesive. Though there could be coming soon a new context menu option of the sort of 'Find matching row' to show and select each other corresponding row as a way to assist matching in those cases when a large number of tracks are involved.

**Comment by ghuDaYuYu** [comment]
My bad English might have made it look as rhetoric questions, they weren't...
I might be missing the point here. Time will tell...
Anyway, thanks you for the improvement suggestion!

**Comment by stephen147** [comment]
If you can implement different row colours it would be an improvement. Sorry I missed the questions.

**Comment by ghuDaYuYu** [comment]
Never mind, my fault not expressing them properly... 👍 
The Different row colours AKA as 'Playlist list' style option can already be found in the preferences window (UI tab).

I've made a note of match percentage column idea. Thanks.

As side note, next updates may focus on writing individual values.
Also related to that, the preview panel UI needs to be revised/reworked.
... and then also the to-do list (including this issue if necessary).

**Comment by ghuDaYuYu** [comment]
I am closing this suggestion as not feasible, too much technical involvement for little gain, or at least I am finding it hard to justify the effort. The other idea about a percentage or ratio of correctness for each match seams interesting... I'll have a look, problem is that the quality of the value will be relative to the quality of the algorithms currently in use, so I am in doubt about what precision will be achieved.
