### ISSUE TITLE
After pressing preview tags the Write tags button is greyed out

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#24]
Using the latest release. https://github.com/ghDaYuYu/foo_discogs/releases/tag/v2.23-mod.16.1

![image](https://user-images.githubusercontent.com/14054664/120530970-ffae5e80-c3d5-11eb-9ca8-f42acbed050d.png)

**Comment by ghDaYuYu** [comment]
This is suppose to be saying... there will be no writes...
Maybe trying to make it clearer I made it more confusing : (

**Comment by stephen147** [comment]
So does that mean that there's no difference in the existing tags vs. the ones in the preview tags window when it's greyed out?

**Comment by ghDaYuYu** [comment]
I normally check like this...
There should be no items in the Writes or Updates columns in the Show TM Stats.
There should be no data displayed clicking on the Difference View (unless there are skipped items in the Show TM Stats Skipped Column).
The Original View and the Results View should display the same info.

The gray Write tags button should assist further and simplify thinks?

**Comment by stephen147** [comment]
Okay, it's just I can't remember this being greyed out before.

**Comment by ghDaYuYu** [comment]
It is alright... thanks for you help improving this component.
Regards

**Comment by ghDaYuYu** [comment]
Fixed documentation in v17 release log.
