### ISSUE TITLE
SUGGESTION - Checkbox for getting artwork on Match Tracks dialog

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#25]
It would be nice to enable or disable grabbing the artwork in this UI, I suppose to use the settings that are in the preferences.

What do you think?

This could also perhaps show the number of artwork that it will get when this is checked or unchecked to info the user.

![image](https://user-images.githubusercontent.com/14054664/120701901-59348d00-c4ab-11eb-9e05-5484e8f2c4b8.png)

**Comment by ghDaYuYu** [comment]
i second that!
maybe even using the list area to show them, like this:
![images list](https://user-images.githubusercontent.com/62167612/122617005-c3dcef80-d08b-11eb-86ff-95e8c0fbd0ed.JPG)

**Comment by stephen147** [comment]
Even better. Maybe a checkbox to allow selection of the different ones if that's possible?

**Comment by ghDaYuYu** [comment]
Yes, a column with the type (primary, secundary...) on the left with a right column with checkboxes. On the right list the local images with filename and size. Good idea Stephen 👍

**Comment by stephen147** [comment]
This will be great. This plugin keeps getting better and better with lots of thanks to you.

**Comment by stephen147** [comment]
> Yes, a column with the type (primary, secundary...) on the left with a right column with checkboxes. On the right list the local images with filename and size. Good idea Stephen 👍

I was thinking would thumbnail previews be easily doable?

**Comment by ghDaYuYu** [comment]
I wish there will be a thumbnail column.
Although the basic functionality will take a while to be ready.
The snapshot below shows what I am currently testing.

A list of available album/artist artwork for the current release, with dimensions,
write options and a preview command (set by keyboard/context menu)

The right panel is next, maybe with a list of predefined items (Front.jpg, Back.jpg, ...)
I dont know.

![review artwork](https://user-images.githubusercontent.com/62167612/123382015-b8a92880-d591-11eb-9472-d1366f12cc30.jpg)

**Comment by stephen147** [comment]
Really cool. Would a panel of previews be possible with the current control you have here. Even if it was 150x150 px it would be great.

**Comment by ghDaYuYu** [comment]
Done in v18 release... Also many thanks to you for making this component better! 💯
