### ISSUE TITLE
Suggestion - Undo previous

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#26]
Self-explanatory really.

It would probably be a big undertaking to do this.

How I think it could work:

1. Run foo_discogs and tag the files.
2. The tags could be saved to the systems temp folder.
3. To undo select the same files and open foo_discogs and click the undo button to resort the tags to the files.

It probably is more involved than that but it would be a nice feature to have.

One level of undo would be fine. :)

**Comment by ghDaYuYu** [comment]
: ) just one level haha. Maybe one day... I´ll have a look.
Not very related, but something much simpler as resetting the match tracks panel could come quite handy.

**Comment by stephen147** [comment]
Yes, that too. haha I don't think more than one level would be needed anyway.

**Comment by gitgetgot** [comment]
> One level of undo would be fine. :)

Here is how I do UNDO one level myself:

-Select the files to tag, open properties window (thats my backup/UNDO) and place that window somewhere on the screen where it don't bother you.
-Tag the files with foo_discogger
-check if they're the way you want them.
---if yes, close the backup/UNDO properties window
---if no, tag again, or copy all (necessary) tags from the backup/UNDO properties window back.

;-) I know, its not like we all want it. complete safety is an illusion 8-]

There exist components ([m-TAGS](https://www.foobar2000.org/components/view/foo_tags), [External Tags](https://www.foobar2000.org/components/view/foo_external_tags)) which does save tags into a text file, but I never had use for it, so it might not help you here.

**Comment by ghuDaYuYu** [comment]
Added to the To Do, thanks for your suggestion!

**Comment by stephen147** [comment]
Thanks for adding this.

How is this implemented? Is there an undo button next time this is run?

**Comment by ghuDaYuYu** [comment]
I see, the closing message got lost somehow while closing this issue...
One reason putting me off implementing undo is that it seams a feature an independent plugin should be providing, also the performance considerations.
Added to the To Do list, anyway, to be considered for future releases,

**Comment by stephen147** [comment]
It's okay. The message left that this was completed led me to think you had it done.

You don't have to implement this if you feel it's not within the scope of it.
