### ISSUE TITLE
Parsing URL doesn't match the URL for hidden tracks

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#27]
I'm trying to parse this url: https://www.discogs.com/release/10512462

As you can see there are 15 tracks but only 14 are getting parsed. See below.

![image](https://user-images.githubusercontent.com/14054664/126063233-e89511bd-2736-49df-b086-74cf3b588162.png)

**Comment by ghDaYuYu** [comment]
I beleive that is caused by a bug in v17, the release on the left seams the 14 track Japan edition, not 10512462. Sorry for the inconvenience, Should be already fixed in v18.
Thanks for reporting!

**Comment by stephen147** [comment]
> I beleive that is caused by a bug in v17, the release on the left seams the 14 track Japan edition, not 10512462. Sorry for the inconvenience, Should be already fixed in v18.
> Thanks for reporting!

That doesn't seem to have worked after updating.

What results are you getting on your end when parsing that url?

**Comment by ghDaYuYu** [comment]
These are the results I get parsing the first Busta url, it seams the right result...
Could it be that files have mixed Release Ids (maybe the first track has different Id than the rest?

(pasting the whole url into the release entry box):
https://www.discogs.com/release/10512462

![busta par](https://user-images.githubusercontent.com/62167612/126892539-60e9e66c-8c89-40b3-9250-0044798f7e6d.JPG)

The Jay-Z release should have 12 tracks ? I am not sure how this is wrong, sorry...

![Jay-Z DC](https://user-images.githubusercontent.com/62167612/126892675-8547ade4-29e3-40c5-b8fb-b6889c7ceddf.JPG)

Never used this option before... here this is activating 'Parse hidden tracks as regular tracks' (Caching configuration option):

![hidden release](https://user-images.githubusercontent.com/62167612/126892689-dfc2447f-bada-4e09-9648-ddf75b670b7a.JPG)

Do you mean that with the 'Parse as regular tracks' option disabled, all extra tracks should be completely removed from the results?

**Comment by stephen147** [comment]
Yes, when the parse hidden tracks as regular tracks is unchecked it only shows 2 hidden tracks when there should be 3 like the first post here.

Checking it, I get the same result as your screenshot.

The Busta Ryhmes album is fine. I think it was something I was doing wrong with that one which was no fault of the plugin.

**Comment by ghDaYuYu** [comment]
Looks like there is a bug hiding there, maybe the tree selection, or the match panel initialization... I noticed it a while ago but couldn't manage to narrow down the steps to replicate it.
I am testing that now but regretfully just getting the expected results.
Made those two modifications in releases and match panels, it might help tracking or noticing when it occurs...

Wider Release descriptions:

![bustatrackmatch](https://user-images.githubusercontent.com/62167612/127113723-c5c11f99-4998-430a-832e-6a8d58614e33.jpg)

Number of tracks in the release panel (only for releases already cached in memory), having some performance issues with this counter, hopefully will get included in next release:

![bustatracknums](https://user-images.githubusercontent.com/62167612/127114107-8e37277c-d059-4f14-9601-91c8266c15d2.jpg)

**Comment by ghDaYuYu** [comment]
... in the Busta Rhyme release, I don´t thing there is a relation with hidden tracks....

> Yes, when the parse hidden tracks as regular tracks unchecked it only shows 2 hidden tracks when there should be 3 like the first post here.

 Sorry... So which ones exactly?  :joy:

**Comment by ghDaYuYu** [comment]
yes, url context menu added... we will solve the hidden tracks issue another time... Thanks for the testing efforts and suggestions again, you´ve proven to be a real hero!
Best regards

<img width="538" alt="matchURL" src="https://user-images.githubusercontent.com/62167612/127216452-330f21ff-11b4-45a9-8251-8efc96cbca8c.png">

**Comment by stephen147** [comment]
Thanks for your great efforts also!

Love the new addition there you've done.

In v18 the Busta Rhymes album seemed to work. In V18.1 it doesn't.

Looking forward to the hidden tracks fix.

**Comment by stephen147** [comment]
I found something strange.

If I sort the album one way. When the track numbers are from highest to lowest it works but when they're sorted in order it doesn't. It seems to work all the time too.

It's for the Busta Rymes album.

**See the two screenshots here:**
![descending order](https://user-images.githubusercontent.com/14054664/127781993-6c04966e-e5ae-4da7-8915-50728a76c394.png)


![ascending order](https://user-images.githubusercontent.com/14054664/127781998-c0cae3cb-0450-49cc-a20b-9c6351fc18aa.png)

**Comment by ghDaYuYu** [comment]
The component retrieves the release id from (just) the first track selected, and use it while initializing the Find Release/Match Track panels. As I mentioned earlier, looking at the screenshots, it seams that track 15 has the Japanese edition DISCOGS_RELEASE_ID, and track 0 the US edition. Have you already checked for multiple release id values in your selection?

**Comment by stephen147** [comment]
> The component retrieves the release id from (just) the first track selected, and use it while initializing the Find Release/Match Track panels. As I mentioned earlier, looking at the screenshots, it seams that track 15 has the Japanese edition DISCOGS_RELEASE_ID, and track 0 the US edition. Have you already checked for multiple release id values in your selection?

That was the issue. Thanks. I retagged them when the album match but the value didn't update.

On checking, I cannot change the behaviour to Write+Update for DISCOGS_RELEASE_ID.

![image](https://user-images.githubusercontent.com/14054664/127784454-31e607bc-4fbd-49b6-bf70-558282018515.png)

**Comment by ghDaYuYu** [comment]
I believe that write+update for the release_id stands on its own merits for a new issue, after this time looking at the component' code I didn't make up my mind about the best way to implement it, as this feature might lead to incoherent data (artist_id, label_id, ...)
You are welcome to open a new issue on this one 👍

**Comment by ghDaYuYu** [comment]
Could you please check the Jay-Z release screenshots I posted above, and please provide some rationale about number of hidden/#tracks? I would say the right number would be 11 tracks not 12... please bare with me this is a feature I hardy used before.

**Comment by stephen147** [comment]
> Could you please check the Jay-Z release screenshots I posted above, and please provide some rationale about number of hidden/#tracks? I would say the right number would be 11 tracks not 12... please bare with me this is a feature I hardy used before.

Here's the discogs release below with how I think they should be parsed.

The plugin is showing 13 tracks.

![image](https://user-images.githubusercontent.com/14054664/127787796-cf18e997-04df-4da2-98f7-4855b7ddf3dd.png)

**Comment by ghDaYuYu** [comment]
Yes, that Discogs release page layout might not be easily replicated in the component' list view, how the 'Hidden Bonus Tracks' row can fit in the current dialog drag & drop and list view song alignments?
There is also an additional difficulty, the hidden track info is in part (only) specified in the notes... so that will need to be parsed too.
(From the release page...)
Notes
The last track (What They Gonna Do) has 3 hidden tracks - La La La (Excuse Me Miss Again), Stop, Panjabi MC - Beware of the Boys (Jay-Z Remix).

I am sorry to say that, this feature (not a bug in my opinion) is not very viable.

**Comment by stephen147** [comment]
Ok, It seems you're correct. Sorry to have bothered you about this non-issue... 😳

I've modified that [release](https://www.discogs.com/release/11099319) so it follows the guidelines [here](https://www.discogs.com/forum/thread/216843) for the rules for adding hidden tracks.

I now get the correct parsing. 
![image](https://user-images.githubusercontent.com/14054664/129716908-3f8d7da5-1c0e-4f22-9b4d-4b0c2500ce1f.png)

The trick is to start the first track and it's hidden tracks with 12.1, 12.2, 12.3 in this cause for the relase in question https://www.discogs.com/release/11099319.

CASE CLOSED.

**Comment by ghDaYuYu** [comment]
Nothing to be sorry... thank you for raising this issue.
I am also leaving here another marker for future reference...
[12.17.1 Hidden and blank tracks](https://support.discogs.com/hc/en-us/articles/360005055373-Database-Guidelines-12-Tracklisting)
