### ISSUE TITLE
DISCOGS_RELEASE_ID - No way of choosing write+update

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#29]
As shown below.

The tag doesn't get written when it exists as there's no way of choosing the write+update as it's greyed out.

![](https://user-images.githubusercontent.com/14054664/127784454-31e607bc-4fbd-49b6-bf70-558282018515.png)

**Comment by ghDaYuYu** [comment]
From v1.0.2 you can use Shift + Click on that entry to enable some of the options in the context menu.
Changing the release_id options will also assign the same value to master_release, artist_id, and label_id though.

**Comment by stephen147** [comment]
Thanks for adding this.

Just curious, why does it need a shift right click?

**Comment by ghDaYuYu** [comment]
might discourage novice users?

**Comment by stephen147** [comment]
No probs. A tooltip to remind other users. Would that be able to get implemented?

**Comment by ghDaYuYu** [comment]
coincidental... new tooltip in the preview panel value column will be included in next release. Also finally not only the size but also the actual dialog position is saved in the preference file.

<img width="739" alt="tt" src="https://user-images.githubusercontent.com/62167612/129822021-1ac62fe1-934b-4271-83d3-ded6f5fe5f1c.png">

Not sure about the overwrite release id tooltip... I never missed the feature myself, what reminder literally would you say would be appropriate? 
Still not sure myself about the implications of allowing such functionality of Apocalypse ; )

**Comment by stephen147** [comment]
> Not sure about the overwrite release id tooltip... I never missed the feature myself, what reminder literally would you say would be appropriate?

I suppose you're right. I won't be changing this again and if I forget how to enable it, I can always come back here and annoy you.. 😂

**Comment by ghDaYuYu** [comment]
Ok, ok... I promise giving it a second thought 😄🤘

**Comment by bassstorm** [comment]
Just in case, I was puzzled also with same question (how to disable those few fields) :-)
