### ISSUE TITLE
Release filter is not autom. filled, when "Auto-search" is not active.

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#32]
Version: 1.0.4
Compiled: Aug 19 2021

A minor glitch, please see attached animated Gif.

![GIF](https://user-images.githubusercontent.com/974980/130280445-5735bd31-70bb-426d-a2cd-9fe71df9dd24.gif)

When "[x] auto-search artist when opening find release dialog" is active, the filter is automaticly set to the album title, which is nice!
Deactivating the "[ ] auto-search artist when opening find release dialog", removes that nice feature :-)

**Comment by ghuDaYuYu** [comment]
[0877aa87ffbf186ca48350bec7c21eb73deff6ab](https://github.com/ghDaYuYu/foo_discogs/commit/0877aa87ffbf186ca48350bec7c21eb73deff6ab)
