### ISSUE TITLE
Unhandled exception in "Expanding master release...": invalid vector subscript

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#33]
Version: 1.0.4
Compiled: Aug 19 2021

I found this hard to reproduce, but finally...
please see (last part of the) attached animated gif (where the error pops up).

![png](https://user-images.githubusercontent.com/974980/130281746-ef1d9e92-01fb-4f58-b52c-5d8e0ae39915.png)

![GIF](https://user-images.githubusercontent.com/974980/130281759-c0c8c5a8-6bc8-47f2-875a-c846def38680.gif)

everything works fine, if I slowly click on the master-releases and do not type any text... :)

**Comment by ghuDaYuYu** [comment]
[c8e8dcd63931840564a657a65bb71b5d86e2f538](https://github.com/ghDaYuYu/foo_discogs/commit/c8e8dcd63931840564a657a65bb71b5d86e2f538)
