### ISSUE TITLE
Lot of crashes, when fetching albums/releases of an artist.

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#36]
Version: 1.0.4
Compiled: Aug 19 2021

When fetching the releases from artists, the fine component often crashes spontaniously.

Seems, it is not the artist which causes the crash, but my impression is, that some fetching-"things" are not finished and when clicking on another artist (impatience, fast, not lazy) the component crashes fb2k.

![crash3](https://user-images.githubusercontent.com/974980/130286296-2a9e1799-c8a4-4b80-828a-29ccf33470f5.gif)

![crash4](https://user-images.githubusercontent.com/974980/130286868-9f40912c-8015-4f75-b823-bd46d6a36d73.gif)

![crash1](https://user-images.githubusercontent.com/974980/130286904-027ea0b6-fbfe-4be8-a87d-228be911a0e4.gif)

**Comment by ghuDaYuYu** [comment]
[c8e8dcd63931840564a657a65bb71b5d86e2f538](https://github.com/ghDaYuYu/foo_discogs/commit/c8e8dcd63931840564a657a65bb71b5d86e2f538)

**Comment by gitgetgot** [comment]
Sorry, I opend up a doublette for this. => https://github.com/ghDaYuYu/foo_discogs/issues/63

But this time, I attached crash reports :-)

**Comment by ghuDaYuYu** [comment]
Take deep breath, mate. Have you taken the time at least to read my comments to your latest issues, some of are in the discussion area, etc.
You are not just pretending to flood this repo with issues, are you?

**Comment by gitgetgot** [comment]
Nope, I don't. I go step by step.
And I presume crashes of a mainprogram (whatever the crashes caused) as a no go. 

I'll read carefully now through all the replies.

**Comment by ghuDaYuYu** [comment]
Yes, be more careful

**Comment by gitgetgot** [comment]
Would you mind to link me to the mentioned discussions?

I'll only found [this open issue](https://github.com/ghDaYuYu/foo_discogs/issues/18#issuecomment-848234009). Its not a discussion and I'm not involved.

Can't find a discussion where you comment about the crashes I experienced.
