### ISSUE TITLE
Invert selecton (Manage Artwork) does not work, when ALL artwork is selected.

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#38]
Version: 1.0.4
Compiled: Aug 19 2021

Manage Artwork Window:

If you have to artworks and select the first one, then right-click and choose "invert selection", the second artwork is selected. and vice versa. thats fine.

Now, select all two artworks and choose "invert selection".
I'd expect none to be selected then, but nothing happens.

Bug, or feature?

![selection](https://user-images.githubusercontent.com/974980/130290234-6abc4f5f-868e-4a4b-ae8e-4504da49eeb6.gif)

**Comment by ghuDaYuYu** [comment]
[b4566bea88697f62808d13e1e70eb821fa41eb51](https://github.com/ghDaYuYu/foo_discogs/commit/b4566bea88697f62808d13e1e70eb821fa41eb51)
