### ISSUE TITLE
Manage Artwork: Can we have a double-click option on Save/Overwrite/Embed ?

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#39]
Hi,
just out of lazyness...

it would be nice, if doubleclicking the columns Save/Overwrite/Embed would activate those options, just like the keyboard-shortcuts do.
Also, a remove/del button would be very convenient.

Thanks :)

P.S.
What does the RESET do?
I expected all chosen Save/Overwrite/Embed-checkboxes would reset to the state before editing, but the RESET does nothing (visual) here.

**Comment by ghuDaYuYu** [comment]
I should restore all items in the left and right list views (restore order, save/overwrite..)
Strange, I seams to work here.

**Comment by ghuDaYuYu** [comment]
[6c84bcbf09cf5a210a739b9c800fb70404a3442c](https://github.com/ghDaYuYu/foo_discogs/commit/6d9dde03d6eca416228a4f52bed4d68ec1e1915a)

**Comment by gitgetgot** [comment]
Thanks,
I made a fresh install of fb2k and it seems RESET works now. No idea what caused the problem.
The doubleclicks now save a lot of time and are very convenient!!
