### ISSUE TITLE
Use either DISCOGS_RELEASE_ID or WWW in the release id / url edit box

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#4]
If DISCOGS_RELEASE_ID exists then the box gets populated with that.

If it doesn't and the URL or WWW tags exist, it would be nice to automatically populate it with that.

See the image for where I'm referring to:
![image](https://user-images.githubusercontent.com/14054664/108376475-f3bdd880-71fa-11eb-80af-dbb31b70bcf3.png)

**Comment by ghDaYuYu** [comment]
Yes, a combo box with past visited or other assistance would be nice!

**Comment by stephen147** [comment]
Past visited would be great.

Also, a separate one for the URL and id would be great. So the WWW tag gets populated and the DISOGS_RELEASE_ID too in the id box.

**Comment by ghDaYuYu** [comment]
Could you provide what sort of urls would be there? do you mean something like
https://www.discogs.com/release/12345678 that particular addon has added, or are they entered manually?

**Comment by stephen147** [comment]
Yes, that could be taken from the WWW tag and placed in the UI. It would be useful if the id doesn't exist so all the user would have to do is click on the next button. The same way now if the ID is there.

**Comment by gitgetgot** [comment]
I have seen files, where ppl. put the discogs-ID-URL in the comment-tag too.

**Comment by ghuDaYuYu** [comment]
Closed for inactivity, feel free to reopen, providing more info, specific data samples, data origin descriptions, etc.

**Comment by stephen147** [comment]
Hi, so this is implemented now?

**Comment by ghuDaYuYu** [comment]
Same problem with the message here, not implemented, just added to the To Do list,
It is planned to add configuration options to specify where to look for Discogs ids as fb2k does with album art. 
So not implemented, but added to the To Do list.
