### ISSUE TITLE
%RELEASE_TITLE% not written to ALBUM tag

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#40]
Version: 1.0.4
Compiled: Aug 19 2021

The ALBUM Tag is not being written, although, it is the default setting.

My tag mappings for ALBUM:
![2021-08-20 22-53-27_Tag Mapping](https://user-images.githubusercontent.com/974980/130293586-8e9bcb2c-a7e5-4e45-aa0d-8491ecc42a37.png)

I have tagged an album "TEST TEST TEST " and the [album](https://www.discogs.com/release/23963) written should be "The State Of E:Motion Vol. 7", but after writing the tags with the fine component, the album is still "TEST TEST TEST "

Video:
![albumnotwritten](https://user-images.githubusercontent.com/974980/130293581-c6fb4edf-52d2-4455-82c3-c1598a29acb4.gif)

EDIT:
also the TITLE is not written always.
my formatting string (which works flawlessly in the old component):
`$ifequal(%TRACK_TOTAL_HIDDEN_TRACKS%,0,%TRACK_TITLE%,$join($extend($array(%TRACK_TITLE%),%<TRACK_HIDDEN_TRACKS_TITLE>%),' / '))`
![2021-08-21 04-16-18_Tag Mapping](https://user-images.githubusercontent.com/974980/130307504-2054f3b4-9ba5-4a56-9283-ecfe1f792cdf.png)

![aain](https://user-images.githubusercontent.com/974980/130307519-4b186fa8-9643-4ce3-905b-b345f1fe792c.gif)

**Comment by ghDaYuYu** [comment]
Are you sure you want a write operation, I would say you need an update instead.

Look at your stats:
Title -> 12 skipped, 37 equal
Album -> 49 skipped


Btw, thanks for taking the time and your effort adding all these issues...
It will take quite some time to check them all though : )

Regards
