### ISSUE TITLE
Find Release window: Sometimes, Master Releases do not open/expand

### ISSUE THREAD

**Issue by gitgetgot** [ghDaYuYu/foo_discogs#43]
Version: 1.0.4
Compiled: Aug 19 2021

Doubleclicking on a Master Release opens its. 
But not in all cases and I have no idea why -on some Master Releases- the + will not expand.

Quite difficult to reproduce.
In the animated Gif, you see me doubleclicking like hell on all of the Master Releases, but only some will open.

After a restart of fb2k everything is working as expected, but then suddenly, the bug comes back again...

No idea how to trigger that bug... sorry. (Maybe its the text-filter...?)

![doubleclick does not work](https://user-images.githubusercontent.com/974980/130296953-b2a30e3f-777f-4ac0-8a84-3035db3fe682.gif)

**Comment by ghuDaYuYu** [comment]
Have you checked (removing the filter and expanding) that there is content inside those nodes (refusing to expand) meeting the search criteria 'st'. All maSTers will meet the criteria, but only those containing releases that also meet the criteria will expand. Not very intuitive I know.
