### ISSUE TITLE
Date is not getting found for this release

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#5]
Here's the release: https://www.discogs.com/release/1596886

And my format for the DATE tag:
```
$trim($if($and(%date%,%RELEASE_LABELS_CATALOG_NUMBER%),$if(%RELEASE_DATE_RAW%,$ifequal($len(%RELEASE_DATE_RAW%),4,%RELEASE_DATE_RAW%-01-01,$ifequal($right(%RELEASE_DATE_RAW%,2),00,$left($replace(%RELEASE_DATE_RAW%,00-00,01-01),7)-01,$replace(%RELEASE_DATE_RAW%,00-00,01-01))),),%date%))
```

**Comment by ghDaYuYu** [comment]
I see, result of my initial quick and dirty fix (write/update bug) to the original code... should be getting closer to the original after last code update.

Would you like to test the panel update? v03 beta can be found [here](https://drive.google.com/file/d/1s8RzeK3XQBunJenVEtXOpMcp2cKhiHx8/view?usp=sharing)

![Preview](https://user-images.githubusercontent.com/62167612/108600967-51d4f200-739a-11eb-94a7-9c61a62d0ef4.JPG)

(Reddish title means different value was found but it wont be updated (write option in TITLE)

**Comment by stephen147** [comment]
Is that a newer version. I've downloaded the latest yesterday and it wasn't getting the DATE.

**Comment by stephen147** [comment]
Fixed in the latest beta release. https://github.com/ghDaYuYu/foo_discogs/issues/6#issuecomment-782746932
