### ISSUE TITLE
View Normal, Difference and Orginal are not working like the original plugin

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#6]
See here, this is the original plugin.
![image](https://user-images.githubusercontent.com/14054664/108377469-f836c100-71fb-11eb-8e60-49f0d12d4ec1.png)

With your mod, these 3 don't work.

Here's my custom mapping file:

[discogs ghDaYuYu Settings.zip](https://github.com/ghDaYuYu/foo_discogs/files/6003791/discogs.ghDaYuYu.Settings.zip)

**Comment by ghDaYuYu** [comment]
I see, result of my initial quick and dirty fix (write/update bug) to the original code... should be getting closer to the original after last code update.

Would you like to test the panel update? v03 beta can be found [here](https://drive.google.com/file/d/1s8RzeK3XQBunJenVEtXOpMcp2cKhiHx8/view?usp=sharing)

![Preview](https://user-images.githubusercontent.com/62167612/108600967-51d4f200-739a-11eb-94a7-9c61a62d0ef4.JPG)

(Reddish title means different value was found but it wont be updated (write option in TITLE)

**Comment by stephen147** [comment]
Thanks. I've tested.

It's not writing the tags afterwards with that.

Before:
![image](https://user-images.githubusercontent.com/14054664/108603863-366de500-73a2-11eb-9e0d-05112098836a.png)

Preview tags:
![image](https://user-images.githubusercontent.com/14054664/108603883-52718680-73a2-11eb-830b-4e3814577e49.png)

After is the same as the before image. Using the same settings file as my OP.

Here's the release page: https://www.discogs.com/release/586244

**Comment by ghDaYuYu** [comment]
Maybe there was a 3rd column in there before....
I've just packed v.03preview (fixes update option), after the v.03beta you downloaded before.
The Write/Update/W+U need more testing sorry, [here](https://drive.google.com/file/d/1s8RzeK3XQBunJenVEtXOpMcp2cKhiHx8/view?usp=sharing) is the link if you want to have a look.

Thanks Stephen for your support...

... about the write and update the following text is taken from a post from fuffi, at hydrogenaud.io,

Quote from: alec.tron on 2017-01-07 22:36:10

    what is the different between 'write, ''update' and 'write & update') ? 

Quote from fuffi:

simple as this: ;-)

- write will only write, not update. (if no tag exists, write a tag. if a tag exists, don't overwrite/update it.)
- update will only update, not write. (if a tag exists, update it. do not create tags, which don't exist in the file)
- write&update will do both. (I don't care, just tag my files with all the tags I specified in the fine component...)

**Comment by stephen147** [comment]
Happy to test it out for you seeing as the other will no longer be getting dev'd.

I've only tested one album but it all appears to be working just fine. The carriage return fix is great.

This issue appears to be closed, thanks for the fix so quickly.
