### ISSUE TITLE
Auto-search artist is not working

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#7]
Hey! again :)

This isn't working. I've updated to the latest version also.

![image](https://user-images.githubusercontent.com/14054664/109398617-eb217c80-7935-11eb-82e6-232911d101c6.png)

**Comment by ghDaYuYu** [comment]
Hello! auto-searh... noted!  : )

**Comment by ghDaYuYu** [comment]
Hi Stephen,
It seams this option should say 'Auto Search artist when opening find release dialog (if no release Id defined already)  : )
I included a new command in the main menu to test this issue... "Write Tags (Update Release Id).
It triggers the search even if a release Id is available, it´s on [v07 Beta](https://drive.google.com/file/d/1s8RzeK3XQBunJenVEtXOpMcp2cKhiHx8/view?usp=sharing)
How would changing the release Id affect the cache, and other Ids,  should then also be updated without user intervention?
I am afraid that allowing easily changing this may introduce metadata inconsistencies... what do you thing?

Thanks for taking the time to test these releases (and sorry for horrible v05 release! 🥇 ),
You ideas and suggestions are much appreciated.

Cheers!

**Comment by stephen147** [comment]
It's fine to auto search. The ID will be populated anyway so the user can always click next at any time if they want to tag with the same release.

I'm not sure what you mean about the cache.

No worries. Just glad that someone has taken on the project and open to making it even better ;)

**Comment by ghDaYuYu** [comment]
Why then in the original release was Release ID write only? We propably find some answers when I go into more depth reviewing the original code : )

**Comment by stephen147** [comment]
I'm sure you'll get to the bottom of it.

**Comment by ghDaYuYu** [comment]
Hi Stephen, v11 is out! this issue should have been solved in this release

**Comment by stephen147** [comment]
Thanks, I've tried testing and my album names are like so:
Beyond The Future EP [INNERVISIONS04]

I put the cat number at the end of them.

When I click the search button for the artist it repopulates the filter with that every time.

This didn't happen before.

**Comment by ghDaYuYu** [comment]
This is what I get 'No Me Iré Mañana (Edición 25º Aniversario)'  with the original v2.23

![STE1](https://user-images.githubusercontent.com/62167612/112229488-5a3b7980-8c33-11eb-9ee1-a63577cb4e5c.jpg)

This with v11:

![2STEPHEN](https://user-images.githubusercontent.com/62167612/112229558-7b9c6580-8c33-11eb-89c2-4708c60feaa0.jpg)

**Comment by frogworth** [comment]
That looks great, but can you check if it's working on single top-level releases now? I noticed with this release, anything in the Filter makes the whole list disappear...
<img width="937" alt="Screen Shot 2021-03-24 at 10 08 00 am" src="https://user-images.githubusercontent.com/6443015/112230465-f5ab0980-8c88-11eb-90e7-21af4cbf2c09.png">
See the "Crazy Baldheads" 12" there. But with the filter:
<img width="936" alt="Screen Shot 2021-03-24 at 10 08 31 am" src="https://user-images.githubusercontent.com/6443015/112230495-06f41600-8c89-11eb-92ad-ec0a369681f3.png">

**Comment by ghDaYuYu** [comment]
The automatic filter search with albums named differently than the master never worked in the original component.
Thats my experience though. There are several factors that can interfere... what I found it works best as I say, is having the album named after the master or as in my second snapshot, have other names but to fill the filter edit box with the master name to locate the release in the list. 
The list is now and it was in the original version filtered by that value in the edit box... but the filter is only applied to the first level (master and non master releases). So you will just get a blank panel when entering a full album name different than the master

**Comment by stephen147** [comment]
Clear the cache and the artist will have to load that artist and the id will not be populated until the whole process is complete.

The OG discogs plugin the ID there from the start of the process and the next button wasn't locked up.

**Comment by frogworth** [comment]
Just to be clear, the release I'm searching for there is not a sub-release. It's a single release with no master, it's there as soon as you search the artist, but filtering for anything makes all releases disappear as far as I can see. Probably just a little bug!

**Comment by ghDaYuYu** [comment]
Hi forgworth, I see what you mean now : |

**Comment by ghDaYuYu** [comment]
Strange... what a naughty list filter, will fix it for next release!

**Comment by frogworth** [comment]
Haha nice, thanks.

**Comment by ghDaYuYu** [comment]
Stephen, thanks again for the testing... 
About the filter box, I am not sure when that will happen.
The position of the column will also need to be saved, and I remember that there were also other column dimensions not being saved... 
I will be sort of a milestone to the mod... modding the original configuration file.

**Comment by stephen147** [comment]
Thanks for your efforts. Having to load artists when they're not in the cache is painful when some artists have 20+ pages.

The OG one allowed the user to click next before that process was complete so looking forward to the fix.

**Comment by ghDaYuYu** [comment]
You can skip the search artist search now, it the release Id is present, with the option to Skip dialog if present

**Comment by ghDaYuYu** [comment]
Sorry, with the 'Skip dialog if RELEASE_ID tag is already present' in the configuration panel  : )

**Comment by ghDaYuYu** [comment]
I’m closing this issue because it has been inactive for a few months.

Please reopen if you want to leave us a comment!

Thank you!
