### ISSUE TITLE
Skip artwork doesn't remember its checked state

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#73]
Maybe this is how you intend it but it would be nice for the checkbox to remember its state between each run.

Currently, it doesn't.

Thanks for the huge update there recently.

**Comment by ghuDaYuYu** [comment]
You are welcome, quite beastie yes, and hope you like it.

The checkbox is confusing... not sure now who had the idea of putting that there : )
Maybe the checkbox label is not precise enough. 
Currently is a tri-state checkbox, with meaning:

( ) skip:   use defaults set at the artwork configuration panel (whatever writes any artwork or not).
(-) skip:  some modification was made in the 'manage artwork' panel (so defaults will be overwritten)
(x) skip:  do not safe any artwork

Does this make any sense clearer or more confusing...

**Comment by stephen147** [comment]
Oh, that is sort of confusing. I don't know if a radio button would be better with those three options?

haha, I think I'm at fault for that ;)

**Comment by ghuDaYuYu** [comment]
do you mean something like this?
( ) Manage artwork         (  ) write artwork  (  ) skip artwork ( x ) custom session settings

That would increase the minimal dialog width and in my opinion distract the user attention from track matching. Maybe we should only show artwork options when manage artwork is enabled

**Comment by stephen147** [comment]
If space is the issue perhaps a dropdown menu?

**Comment by ghuDaYuYu** [comment]
Yes... I am also considering that at some point in a future release, updates to the configuration panel will be globally applied instantly, without the need to close/reopen other panels. That would make this option unnecessary.
The idea is to be able to occasionally bypass artwork settings, not to compete with the config panel. We will revise this issue later, if you dont mind... ui modifications are best done calmly and patiently.
 👍 Thanks for you suggestion!

**Comment by ghuDaYuYu** [comment]
Some button persistence has been added in version [1.0.14](https://github.com/ghDaYuYu/foo_discogs/releases/tag/1.0.14).
Not always saving the last action performed on the button, as defining custom saves also modifies its state. Might save a few clicks anyway. 
Lightly tested it so some revisions will probably be needed.

**Comment by ghuDaYuYu** [comment]
Closing, feature seems to working as expected
