### ISSUE TITLE
Crashes whenever downloading artwork

### ISSUE THREAD

**Issue by frogworth** [ghDaYuYu/foo_discogs#76]
The latest version of the component crashes whenever it downloads artwork. This makes it rather difficult to use.

**Comment by ghuDaYuYu** [comment]
I've never came across crashes, as in your description, saving artwork on default configurations.
I might be wrong, but I would rather suspect an unmatched number of Discogs release track elements vs local files. Next release will address the later, including quite a few related crash scenarios as well as other Tag Mapping panel Drag & Drop fixes.

Anyway I will double check this issue by the time v108 is released... thanks for your feedback

**Comment by frogworth** [comment]
Thanks! That mismatch might be it... It seems very consistent for me. Is there a configuration I could change? Or should I just wait for v1.08? No worries!

**Comment by ghuDaYuYu** [comment]
About v1.08 release, maybe available by July?

I attach v1.08-preview (to be run on fresh portable installation). Work on disc, track and hidden tracks parsing, also on the new detailed preview panel is currently underway... Might be worth running nonetheless, to check if this particular issue has already been fixed in recent commits.

🔮[zipped_foo_discogger.zip](https://github.com/ghDaYuYu/foo_discogs/files/8933444/zipped_foo_discogger.zip)

**Comment by frogworth** [comment]
Thanks! Unfortunately it crashed for me when I tried tagging something just now too.
All tagging is completed just fine, then it goes to retrieve the images, and crashes.

**Comment by frogworth** [comment]
[failure_00000072.txt](https://github.com/ghDaYuYu/foo_discogs/files/8934734/failure_00000072.txt)
FYI

**Comment by ghuDaYuYu** [comment]
I believe that crash was triggered by an 'only artist artwork available' save operation scenario as in the Limousine Black edition... still the report seam to belong to the Aquadelic Pink release ?

While at it, also fixed invalid artwork filenames saving artwork from preview panel.

Preview including both fixes:
[zipped_v108prev](https://github.com/ghDaYuYu/foo_discogs/files/8935763/zipped_foo_discogger_108prev2.zip)

**Comment by frogworth** [comment]
OK, unfortunately that one crashes too.
I have disabled fetching artist images and that has stopped it crashing.
I had it set to embed artist images, not to save to disk for what it's worth.
I'm not concerned about not fetching them though, so it's fine to have it disabled!

[failure_00000073.txt](https://github.com/ghDaYuYu/foo_discogs/files/8937477/failure_00000073.txt)

**Comment by frogworth** [comment]
Heya, yup this one didn't crash!
It did do some weird things:

- It gave me an error about not being able to give multiple files the same name. This might be for the cover image rather than the artist images.
- It actually embedded the cover art in the first track of the album, even though I don't have cover embedding enabled.

**Comment by ghuDaYuYu** [comment]
Hopefully, first one found and fixed. 
Not too sure about the second error, fixed wrong embed overwrites with both 'Embed in file' and 'Save all images' options enabled.

[zipped_v108prev](https://github.com/ghDaYuYu/foo_discogs/files/8962578/zipped_v108prev.zip)

**Comment by frogworth** [comment]
Very cool thanks!

**Comment by ghuDaYuYu** [comment]
You are welcome! It will take much forever to get this working properly!
Just found a couple new bugs as I am writing : )

**Comment by ghuDaYuYu** [comment]
(cont. to previous post)

Bug found:

- Save artwork defaults are not properly initialized on releases exceeding former v1.07 image limits.

Fix preview:
[zipped_v108prev.zip](https://github.com/ghDaYuYu/foo_discogs/files/8966778/zipped_v108prev.zip)

**Comment by frogworth** [comment]
Thanks, it's definitely not crashing for me now!
Still buggy though. It seems to be ignoring my filenames. I've got:
`cover$ifequal(%IMAGE_NUMBER%,1,,_%IMAGE_NUMBER%)`
as my cover filename(s), and it's saving front.jpg.

**Comment by ghuDaYuYu** [comment]
Hi, hope this version fixes embedding and cover names.
Also some ongoing unrelated (track parsing) code has been removed.
Preview looks already a good v1.07 replacement,

🧂[zipped_v108prev](https://github.com/ghDaYuYu/foo_discogs/files/8980460/zipped_v108prev.zip)

**Comment by frogworth** [comment]
Nice :)
This does seem to work as expected for me. Filenames worked right, existing cover was not overwritten, and importantly, no crash!

Thanks for your hard work.

**Comment by frogworth** [comment]
No problem, glad to have been able to help a bit!
