### ISSUE TITLE
%RELEASE_NOTES% has some extra spaces

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#8]
Here's the release where the notes don't have extra spaces.
https://www.discogs.com/Glen-Campbell-Meet-Glen-Campbell/release/4866367

The plugin returns for the 1st line:
```
Tracks 13-15 taken from Sessions@AOL.  Courtesy of AOL Music
```

Instead of what's shown.
```
Tracks 13-15 taken from Sessions@AOL. Courtesy of AOL Music
```

I'm using this format for it in the meantime.

This won't nuke the carriage returns. Just ` `.

`$trim($multi_replace_exp(%RELEASE_NOTES%, +, ))`

**Comment by ghDaYuYu** [comment]
You wont be able, they´re already in pineapple under the sea!

I´ll have a look...
Cheers!

**Comment by ghDaYuYu** [comment]
It seams this is old known issue cause by buggy web entry forms, we may encounter this again in other fields.
Not in notes anymore, period + double space will be removed from next release,
Good catch!

**Comment by stephen147** [comment]
Thanks for the hard work you're putting into this!

If you ever have a donation link I'd be happy to contribute.
