### ISSUE TITLE
Error: HTTP Error (403)

### ISSUE THREAD

**Issue by buckssss** [ghDaYuYu/foo_discogs#85]
Cannot make any request with foo_discogger, getting Error 403.
When making request with REST client it shows HTML page with CloudFlare page instead of JSON saying: 
"api.discogs.com needs to review the security of your connection before proceeding". When open api.discogs.com in browser it opens json.

**Comment by ghuDaYuYu** [comment]
People at Discogs have been working on its firewall rules around that date, api access should be working fine again. Maybe you should add some additional CloudFlare Ip ranges if you control you outgoing traffic.

**Comment by ghuDaYuYu** [comment]
Thanks for reporting!
Closing issue as it has been inactive for 30 days.
