### ISSUE TITLE
Crash on release ID 23935850

### ISSUE THREAD

**Issue by icedream** [ghDaYuYu/foo_discogs#86]
Opening up the "Find releases" dialog through the context menu Tagging > Discogger > Write tags... and looking up Discogs release ID `23935850` consistently crashes foobar.

**Comment by icedream** [comment]
Attaching crash report log/dmp here: [crash report.zip](https://github.com/ghDaYuYu/foo_discogs/files/9937809/crash.report.zip).

**Comment by icedream** [comment]
Attaching crash report with minimal foobar2000 setup + this plugin: [crash report.zip](https://github.com/ghDaYuYu/foo_discogs/files/9937830/crash.report.zip)

**Comment by ghuDaYuYu** [comment]
Please go to the release section and download v1.0.14.8, the crash should be solved then, if not, please report back,
thanks for reporting and crash files!

**Comment by icedream** [comment]
This indeed fixes it, thank you very much!

I don't know if the release has indeed been there for a bit now, sorry to have missed it if that's the case.

**Comment by ghuDaYuYu** [comment]
I thought that fix was already included in v.1.0.14 so I've just promoted v1.0.14.8 pre-release to release 10 min ago, so I the one to blame here. A proper v1.0.15 was planned, but it may still take some time to be ready.
Thanks to your report again, will also others stumbling into the same problem 👍
