### ISSUE TITLE
Error: Authorization Failed (401)

### ISSUE THREAD

**Issue by tommitytom** [ghDaYuYu/foo_discogs#87]
I get this whenever I try to search:
```
(FATAL) Error: Authorization Failed (401) [Is OAuth working?](url: https://api.discogs.com/database/search?type=artist&q=Mort%20Garson&per_page=100)

[ESCAPE to close]
```

The OAuth test in the `Configure` panel seems to work fine, and returns "OAuth is working!"

**Comment by ghuDaYuYu** [comment]
It is working here...

![401_test](https://user-images.githubusercontent.com/62167612/210533858-41886f7e-0150-484f-8ccd-149114aeb1de.png)

Might be temporal or IP address/VPN releated?
I have come (just now) across issues related to the latest,
running authenticated queries (as the author search query) from standard connections has fixed the issue for both standard and VPN connections. 

Another option I would try is to re-authorize the component (OAuth setup panel).
Sorry I couldn't be of more help and thanks for reporting the issue.

Please don't hesitate to reach out if the issue persist.

**Comment by ghuDaYuYu** [comment]
Thanks for reporting!
Closing issue as it seams that no longer persists.
