### ISSUE TITLE
Resizing the match tracks window has a button floating in the files listview

### ISSUE THREAD

**Issue by stephen147** [ghDaYuYu/foo_discogs#9]
See here when the dialog is resized.

Notice the remove button floating.

![image](https://user-images.githubusercontent.com/14054664/110816178-04ee8800-8283-11eb-8d9b-1b17e1d4ea4d.png)

**Comment by ghDaYuYu** [comment]
Thanks, stephen, [fixed](https://github.com/ghDaYuYu/foo_discogs/commit/3386ede19e8086f265b507357c5fd58bd5caca05)!
