### ISSUE TITLE
Can't search with url

### ISSUE THREAD

**Issue by troufiniou** [ghDaYuYu/foo_discogs#90]
Hi !

I tried your plugin and IDK if it's a bug or not, I can't search using the full link, I need to put the Id of the release.

Example : https://www.discogs.com/fr/release/34425-Miro-Shining-Its-Like-XTC
I need to use 34425

Thanks

**Comment by ghuDaYuYu** [comment]
Hi,
Yes, that's bug. The input box is not recognizing the local code (works without the /fr segment).
I will have a look asap.
Thanks for reporting!

**Comment by ghuDaYuYu** [comment]
Should be fixed in the latest release (v1.0.16).
Regards!
