### ISSUE TITLE
Request: fetch DISCOGS_RELEASE_ID using existing MUSICBRAINZ_ALBUMID

### ISSUE THREAD

**Issue by gitttt54** [ghDaYuYu/foo_discogs#98]
Hi,
I'd like to propose a feature request:

may it be possible in further version to add a nice new feature which allows the component to automaticly fetch the connected DISCOGS_RELEASE_ID from a MusicBrainz release? (given, the music files have a suitable tag)

MB offers **external links** on most releases, like [here](https://musicbrainz.org/release/6cac618a-a208-42c0-b48c-62ee0441f490).

IF the component foo_discogger could just check for an existing MB tag MUSICBRAINZ_ALBUMID and fetch the corresponding DISCOGS_RELEASE_ID automaticly (or just enters that ID into the Release id/url) that would be great timesaver and would save a lot of manually work for the users which like to have both their MB+DG tags coherent.

Thank you!

![external](https://user-images.githubusercontent.com/96403800/226611535-5c19176a-b02e-43a4-bd53-8cae05d3d2ab.png)

**Comment by ghuDaYuYu** [comment]
An existing MB tag MUSICBRAINZ_ALBUMID suggests the best and probably the only occasion to both write DISCOGS_RELEASE_ID and ensure MB+DG tags coherency was missed.
AFAIK there is nothing foo_discogger can do about it.
